name: aurora
description: A Structure and Architecture for default Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.3
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.1
  go_router_builder: ^2.3.1
  build_verify: ^3.1.0

flutter:
  generate: true
  uses-material-design: true
